version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - energynetwork

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - energynetwork

  energymonitor:
    build: .
    container_name: energymonitor_app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
    networks:
      - energynetwork

networks:
  energynetwork:
    driver: bridge

